export const getModuleForTemplateType = (templateType: string): string => {
  const mapping: Record<string, string> = {
    // OPERATIONS
    TASK_PLAN: 'OPERATIONS',
    TASK_REPORT: 'OPERATIONS',

    // PRE_REPAIR (Tổng tháo)
    ENGINE_PRE_REPAIR: 'PRE_REPAIR',
    CHASSIS_PRE_REPAIR: 'PRE_REPAIR',
    ELECTRICAL_PRE_REPAIR: 'PRE_REPAIR',
    BODY_PRE_REPAIR: 'PRE_REPAIR',
    INTERIOR_PRE_REPAIR: 'PRE_REPAIR',
    PAINT_PRE_REPAIR: 'PRE_REPAIR',
    GENERAL_DISASSEMBLY_REPAIR: 'PRE_REPAIR',

    // ENGINE_REPAIR (Sửa máy)
    ENGINE_COMPONENT_DISASSEMBLY: 'ENGINE_REPAIR',
    PARTS_CLEANING_REPAIR: 'ENGINE_REPAIR',
    ENGINE_COMPONENT_REPAIR: 'ENGINE_REPAIR',
    LAP_RAP: 'ENGINE_REPAIR',
    KIEM_TRA_SAU_LAP: 'ENGINE_REPAIR',

    // CHASSIS_REPAIR (Sửa gầm)
    TONG_THAO_CUM_GAM: 'CHASSIS_REPAIR',
    TAY_RUA_GAM: 'CHASSIS_REPAIR',
    SUA_CHUA_GAM: 'CHASSIS_REPAIR',
    LAP_RAP_GAM: 'CHASSIS_REPAIR',
    KIEM_TRA_GAM: 'CHASSIS_REPAIR',

    // ELECTRICAL_REPAIR (Sửa điện)
    TONG_THAO_CUM_DIEN: 'ELECTRICAL_REPAIR',
    TAY_RUA_DIEN: 'ELECTRICAL_REPAIR',
    SUA_CHUA_DIEN: 'ELECTRICAL_REPAIR',
    KIEM_TRA_DIEN: 'ELECTRICAL_REPAIR',

    // BODY_REPAIR (Sửa vỏ, sơn)
    XU_LY_BE_MAT: 'BODY_REPAIR',
    KIEM_TRA_THAN_VO: 'BODY_REPAIR',
    TAY_RUA_SON: 'BODY_REPAIR',
    CHONG_GI: 'BODY_REPAIR',
    SON_LEN_MAU: 'BODY_REPAIR',
    KIEM_TRA_NOI_THAT_SON: 'BODY_REPAIR',

    // ASSEMBLY (Tổng lắp)
    PHIEU_TONG_LAP: 'ASSEMBLY',

    // TESTING (Kiểm tra thử nghiệm)
    THU_NGHIEM_TONG_THE: 'TESTING',
  };

  return mapping[templateType] || 'UNKNOWN_MODULE';
};
